# Generated by Django 4.1.7 on 2023-03-06 15:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TruckModel",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Название модели самосвала",
                    ),
                ),
                (
                    "capacity_tons",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Максимальная загрузка самосвала данной модели в тоннах",
                    ),
                ),
            ],
            options={
                "verbose_name": "Модель самосвалов",
                "verbose_name_plural": "Модели самосвалов",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Truck",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Бортовой номер самосвала",
                    ),
                ),
                (
                    "current_load_tons",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Текущая загрузка самосвала в тоннах",
                    ),
                ),
                (
                    "truck_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trucks.truckmodel",
                        verbose_name="Модель самосвала",
                    ),
                ),
            ],
            options={
                "verbose_name": "Самосвал",
                "verbose_name_plural": "Самосвалы",
                "ordering": ["id"],
            },
        ),
    ]
